### ISSUE TITLE
Generated types are incorrect when both `readOnly` and `writeOnly` are used

### ISSUE THREAD

**Issue by bdm-k** [oazapfts/oazapfts#453]
Hello, 

I'm using version 4.7.4 and I encountered a bug.  
Let me take the following schema object for example. 
```YAML
Login:
  type: object
  properties:
    email:
      type: string
      writeOnly: true
    password:
      type: string
      writeOnly: true
    message:
      type: string
      readOnly: true
      description: tells whether the login was successful
  required:
    - email
    - password
    - message
```
`email` and `password` are write-only. `message` is read-only. None of the properties are used in both read and write. So, the expected generation result is as follows. 
```TypeScript
export interface Login {}
export interface LoginWrite extends Login {
    email: string;
    password: string;
}
export interface LoginRead extends Login {
    message: string;
}
```
But the actual result is
```TypeScript
export interface Login {
    email: string;
    password: string;
    message: string;
}
export interface LoginWrite extends Login {
    email: string;
    password: string;
}
export interface LoginRead extends Login {
    message: string;
}
```
